modLoader="javafml"
loaderVersion="[47.1.28,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvyGTS"

[[mods]]
modId="envygts"
version="4.4.0"
displayName="EnvyGTS"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvyGTS
'''

[[dependencies.envygts]]
modId="forge"
mandatory=true
versionRange="[47.1.28,)"
ordering="NONE"
side="BOTH"

[[dependencies.envygts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"