modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvyGTS"

[[mods]]
modId="envygts"
version="4.1.8"
displayName="EnvyGTS"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvyGTS
'''

[[dependencies.envygts]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.envygts]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"